name: Pull request

on: 
  pull_request:
    branches: [main]

jobs:
  linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  unit-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  cypress-tests:
    name: Run Cypress tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
         run: npm ci
      - name: Start local server
         run: npm start &
         background: true
      - name: Wait for server to start
         run: npx wait-on http://localhost:3000
      - name: Run cypress tests
         run: npx cypress run
      - name: Stop local server
         run: kill $(lsof -t -i:3000) || true